import './globals.css'
import Template from '@/app/lib/Template'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <Template>
      {children}
    </Template>
  )
}
