export const ACCEPTED_PAPERS = [
    {
        title: "A Recipe for Success? Exploring Strategies for Improving Non-Visual Access to Cooking Instructions",
        authors: [
            "Franklin Mingzhe Li",
            "Ashley Wang",
            "Patrick Carrington",
            "Shaun K. Kane",
        ],
    },
    {
        title: "AccessShare: Co-designing Data Access and Sharing with Blind People",
        authors: [
            "Rie Kamikubo",
            "Farnaz Zamiri Zeraati",
            "Kyungjun Lee",
            "Hernisa Kacorri",
        ],
    },
    {
        title: "Accessibility through Awareness of Noise Sensitivity Management and Regulation Practices",
        authors: [
            "Emani Dotch",
            "Avery Mavrovounioti",
            "Weijie Du",
            "Elizabeth Ankrah",
            "Jazette Johnson",
            "Aehong Min",
            "Gillian R Hayes",
        ],
    },
    {
        title: "Accessible Nonverbal Cues to Support Conversations in VR for Blind and Low Vision People",
        authors: [
            "Crescentia Jung",
            "Jazmin Collins",
            "Ricardo E. Gonzalez Penuela",
            "Jonathan Isaac Segal",
            "Andrea Stevenson Won",
            "Shiri Azenkot",
        ],
    },
    {
        title: "AltCanvas: A Tile-Based Image Editor with Generative AI for Blind or Visually Impaired People",
        authors: [
            "Seonghee Lee",
            "Maho Kohga",
            "Steve Landau",
            "Sile O'Modhrain",
            "Hariharan Subramonyam",
        ],
    },
    {
        title: "An Ecosystem of Support: A U.S. State Government-Supported DIY-AT Program for Residents with Disabilities",
        authors: ["Erin Higgins", "Marie E. Sakowicz", "Foad Hamidi"],
    },
    {
        title: "Audio Description Customization",
        authors: [
            "Rosiana Natalie",
            "Ruei-Che Chang",
            "Smitha Sheshadri",
            "Anhong Guo",
            "Kotaro Hara",
        ],
    },
    {
        title: "Beadwork Bridge: Understanding and Exploring the Opportunities of Beadwork in Enriching School Education for Blind and Low Vision (BLV) People",
        authors: [
            "Shumeng Zhang",
            "Weiyue Lin",
            "Zisu Li",
            "Ruiqi Jiang",
            "Chen Liang",
            "Mingming Fan",
            "Raul Masu",
        ],
    },
    {
        title: "Brain Body Jockey project: Transcending Bodily Limitations in Live Performance via Human Augmentation",
        authors: [
            "Giulia Barbareschi",
            "Songchen Zhou",
            "Ando Ryoichi",
            "Midori Kawaguchi",
            "Mark Armstrong",
            "Mikito Ogino",
            "Shunsuke Aoiki",
            "Eisaku Ohta",
            "Harunobu Taguchi",
            "Youichi Kamiyama",
            "Masatane Muto",
            "Kentaro Yoshifuji",
            "Kouta Minamizawa",
        ],
    },
    {
        title: "Breaking the News Barrier: Towards Understanding News Consumption Practices among BVI Individuals in India",
        authors: ["Peya Mowar", "Meghna Gupta", "Mohit Jain"],
    },
    {
        title: "Characterizing 'Motor Ability' for Ability-Based Design",
        authors: ["Claire L. Mitchell", "Jacob O. Wobbrock"],
    },
    {
        title: "ChartA11y: Designing Accessible Touch Experiences of Visualizations with Blind Smartphone Users",
        authors: [
            "Zhuohao Zhang",
            "John R. Thompson",
            "Aditi Shah",
            "Manish Agrawal",
            "Alper Sarikaya",
            "Jacob O. Wobbrock",
            "Edward Cutrell",
            "Bongshin Lee",
        ],
    },
    {
        title: "Co-designing Programmable Fidgeting Experience with Swarm Robots for Adults with ADHD",
        authors: ["Samira Pulatova", "Lawrence H. Kim"],
    },
    {
        title: "Co-designing Robot Dogs with and for Neurodivergent Individuals: Opportunities and Challenges",
        authors: [
            "Ha-Kyung Kong",
            "Derek Xie",
            "Ankith Chandra",
            "Rachel Lowy",
            "Arielle F. Maignan",
            "Sehoon Ha",
            "Chung Hyuk Park",
            "Jennifer G. Kim",
        ],
    },
    {
        title: "Context-Aware Image Descriptions",
        authors: ["Ananya Gubbi Mohanbabu", "Amy Pavel"],
    },
    {
        title: "Design and Evaluation of an Automatic Text Simplification Prototype with Deaf and Hard-of-hearing Readers",
        authors: [
            "Oliver Alonzo",
            "Sooyeon Lee",
            "Akhter Al Amin",
            "Mounica Maddela",
            "Wei Xu",
            "Matt Huenerfauth",
        ],
    },
    {
        title: "Design considerations for photosensitivity warnings in visual media",
        authors: [
            "Laura South",
            "Caglar Yildirim",
            "Amy Pavel",
            "Michelle A. Borkin",
        ],
    },
    {
        title: "Designing Accessible Adaptations for an Electronic Toolkit with Blind and Low Vision Users",
        authors: [
            "Jacqueline Johnstone",
            "Madhuka Nadeeshani",
            "Hanmin Chen",
            "Mohith Vemula",
            "Erica J. Tandori",
            "Kate Stephens",
            "Hashini Senaratne",
            "Kirsten Ellis",
            "Swamy Ananthanarayan",
        ],
    },
    {
        title: "Development and Evaluation of the Mobile Tech Support Questionnaire for Older Adults (MTSQ)",
        authors: [
            "Hasti Sharifi",
            "Joseph E. Michaelis",
            "Debaleena Chattopadhyay",
        ],
    },
    {
        title: "DREEM: Moving from Empathy to Enculturation in Disability Related Human-Centered Design",
        authors: [
            "Leya Breanna",
            "Baltaxe-Admony",
            "Jared Duval",
            "Kathryn E. Ringland",
        ],
    },
    {
        title: "Dude, Where's My Luggage? An Autoethnographic Account of Airport Navigation by a Traveler with Residual Vision",
        authors: ["Cameron Tyler Cassidy", "Stacy Branham"],
    },
    {
        title: "EditScribe: Non-Visual Image Editing with Natural Language Verification Loops",
        authors: ["Ruei-Che Chang", "Yuxuan Liu", "Lotus Zhang", "Anhong Guo"],
    },
    {
        title: "EmoBridge: Bridging the Communication Gap between Students with Disabilities and Peer Note-Takers Utilizing Emojis and Real-Time Sharing",
        authors: [
            "Hyungwoo Song",
            "Minjeong Shin",
            "Hyehyun Chu",
            "Jiin Hong",
            "Jaechan Lee",
            "Jinsu Eun",
            "Hajin Lim",
        ],
    },
    {
        title: "Enabling Uniform Computer Interaction Experience for Blind Users through Large Language Models",
        authors: [
            "Satwik Ram Kodandaram",
            "Utku Uckun",
            "Xiaojun Bi",
            "IV Ramakrishnan",
            "Vikas Ashok",
        ],
    },
    {
        title: "Engaging with Children's Artwork in Mixed Visual-Ability Families",
        authors: [
            "Arnavi Chheda-Kothary",
            "Jacob O. Wobbrock",
            "Jon E. Froehlich",
        ],
    },
    {
        title: "Envisioning Collective Communication Access: A Theoretically-Grounded Review of Captioning Literature from 2013-2023",
        authors: ["Emma J McDonnell", "Leah Findlater"],
    },
    {
        title: "Ethical Concerns when Working with Mixed-Ability Groups of Children",
        authors: [
            "Ana O. Henriques",
            "Patricia Piedade",
            "Filipa Rocha",
            "Isabel Neto",
            "Hugo Nicolau",
        ],
    },
    {
        title: "Exploring how People with Spinal Cord Injuries Seek Support on Social Media",
        authors: [
            "Tamanna Motahar",
            "Sara Nurollahian",
            "YeonJae Kim",
            "Marina Kogan",
            "Jason Wiese",
        ],
    },
    {
        title: "Exploring Sound Masking Approaches to Support People with Autism in Managing Noise Sensitivity",
        authors: [
            "Anna Y Park",
            "Andy Jin",
            "Jeremy Zhengqi Huang",
            "Jesse Carr",
            "Dhruv Jain",
        ],
    },
    {
        title: "Exploring The Affordances of Game-Aware Streaming to Support Blind and Low Vision Viewers: A Design Probe Study",
        authors: [
            "Noor Hammad",
            "Frank Elavsky",
            "Sanika Moharana",
            "Jessie Chen",
            "Seyoung Lee",
            "Patrick Carrington",
            "Dominik Moritz",
            "Jessica Hammer",
            "Erik Harpstead",
        ],
    },
    {
        title: "Exploring Videoconferencing for Older Adults with Cognitive Concerns Using a Dramaturgical Lens",
        authors: ["Ruipu Hu", "Ge Gao", "Amanda Lazar"],
    },
    {
        title: "From Information Seeking to Empowerment: Using Large Language Model Chatbot in Supporting Wheelchair Life in Low Resource Settings",
        authors: ["Wen Mo", "Aneesha Singh", "Catherine Holloway"],
    },
    {
        title: "Help and The Social Construction of Access: A Case-Study from India",
        authors: [
            "Vaishnav Kameswaran",
            "Jerry Robinson",
            "Nithya Sambasivan",
            "Gaurav Aggarwal",
            "Meredith Ringel Morris",
        ],
    },
    {
        title: '"I Am Human, Just Like You": What Intersectional, Neurodivergent Lived Experiences Bring to Accessibility Research',
        authors: ["Lindy Le"],
    },
    {
        title: '"I look at it as the king of knowledge": How Blind People Use and Understand Generative AI Tools',
        authors: ["Rudaiba Adnin", "Maitraye Das"],
    },
    {
        title: "I tried everything. Nothing works: Challenges and Creative Processes from Digital Artists with Upper Limb Motor Impairments",
        authors: ["Rodolfo Cossovich", "Shanel Wu", "Audrey Girouard"],
    },
    {
        title: "\"I Try to Represent Myself as I Am\": Self-Presentation Preferences of People with Invisible Disabilities through Embodied Social VR Avatars",
        authors: [
            "Ria J. Gualano",
            "Lucy Jiang",
            "Kexin Zhang",
            "Tanisha Shende",
            "Andrea Stevenson Won",
            "Shiri Azenkot",
        ],
    },
    {
        title: '"I Wish You Could Make the Camera Stand Still": Envisioning Media Accessibility Interventions with People with Aphasia',
        authors: [
            "Alexandre Nevsky",
            "Filip Bircanin",
            "Madeline N. Cruice",
            "Stephanie Wilson",
            "Elena Simperl",
            "Timothy Neate",
        ],
    },
    {
        title: "Inclusion as a Process: Co-Designing an Inclusive Robotic Game with Neurodiverse Classrooms",
        authors: [
            "Patricia Piedade",
            "Isabel Neto",
            "Ana Cristina Pires",
            "Rui Prada",
            "Hugo Nicolau",
        ],
    },
    {
        title: "Intersecting Liminality: Acquiring a Smartphone as a Blind or Low Vision Older Adult",
        authors: ["Isabela Figueira", "Yoonha Cha", "Stacy Branham"],
    },
    {
        title: "Is it Part of Me? Exploring Experiences of Inclusive Avatar Use For Visible and Invisible Disabilities in Social VR",
        authors: [
            "Katrin Angerbauer",
            "Phoenix Van Wagoner",
            "Tim Halach",
            "Jonas Vogelsang",
            "Natalie Hube",
            "Andria Smith",
            "Ksenia Keplinger",
            "Michael Sedlmair",
        ],
    },
    {
        title: '"It\'s an independent living skill, but covered with fun!": Prompting At-Home Skill Development for Children with Vision Impairment',
        authors: ["Vinitha Gadiraju", "Lucia Jayne", "Shaun K. Kane"],
    },
    {
        title: '"It\'s like Goldilocks:" Bespoke Slides for Fluctuating Audience Access Needs',
        authors: [
            "Kelly Avery Mack",
            "Kate S. Glazko",
            "Jamil Islam",
            "Megan Hofmann",
            "Jennifer Mankoff",
        ],
    },
    {
        title: "Looking Past Screens: Exploring Mixed Reality and Discreet AAC Devices",
        authors: [
            "Humphrey Curtis",
            "Adam D.G. Jenkins",
            "Seray B. Ibrahim",
            "Timothy Neate",
        ],
    },
    {
        title: "Low Vision Boxing: Participatory Design of Adaptive Kickboxing Experiences with Low Vision Person",
        authors: [
            "Ayaka Tsutsui",
            "Kenta Yamamoto",
            "Yinan Zhao",
            "Ippei Suzuki",
            "Kengo Tanaka",
            "Yoichi Ochiai",
        ],
    },
    {
        title: "MAIDR Meets AI: Exploring Multimodal LLM-Based Data Visualization Interpretation by and with Blind and Low-Vision Users",
        authors: [
            "JooYoung Seo",
            "Sanchita S. Kamath",
            "Aziz N. Zeidieh",
            "Saairam Venkatesh",
            "Sean McCurry",
        ],
    },
    {
        title: "Misfitting With AI: How Blind People Verify and Contest AI Errors",
        authors: [
            "Rahaf Alharbi",
            "Pa Lor",
            "Jaylin Herskovitz",
            "Sarita Schoenebeck",
            "Robin N. Brewer",
        ],
    },
    {
        title: '"Not Only Annoying but Dangerous": devising an ecology of protections for photosensitive social media users',
        authors: [
            "Rua Mae Williams",
            "Chorong Park",
            "Laila Sameer Dodhy",
            "Monaami Pal",
            "Atharva Anand Dnyanmote",
            "Angel Lam",
            "Sean Joo",
        ],
    },
    {
        title: "Our Stories, Our Data: Co-designing Visualizations with People with Intellectual and Developmental Disabilities",
        authors: [
            "Keke Wu",
            "Ghulam Jilani Quadri",
            "Arran Zeyu Wang",
            "David Kwame Osei-Tutu",
            "Emma Petersen",
            "Varsha Koushik",
            "Danielle Albers Szafir",
        ],
    },
    {
        title: "Painting with Cameras and Drawing with Text: AI Use in Accessible Creativity",
        authors: [
            "Cynthia L. Bennett",
            "Renee Shelby",
            "Negar Rostamzadeh",
            "Shaun K. Kane",
        ],
    },
    {
        title: "Scaffolding Digital Literacy Through Digital Skills Training for Disabled People in the Global South",
        authors: [
            "Laxmi Gunupudi",
            "Maryam Bandukda",
            "Giulia Barbareschi",
            "Tigmanshu Bhatnagar",
            "Aanchal X",
            "Satish Mishra",
            "Amit Prakash",
            "Catherine Holloway",
        ],
    },
    {
        title: "SeaHare: An omidirectional electric wheelchair integrating independent, remote and shared control modalities",
        authors: [
            "Giulia Barbareschi",
            "Ando Ryoichi",
            "Midori Kawaguchi",
            "Minato Takeda",
            "Kouta Minamizawa",
        ],
    },
    {
        title: "SMART-TBI: Design and Evaluation of the Social Media Accessibility and Rehabilitation Toolkit for Users with Traumatic Brain Injury",
        authors: [
            "Yaxin Hu",
            "Hajin Lim",
            "Lisa Kakonge",
            "Jade T. Mitchell",
            "Hailey L. Johnson",
            "Lyn Turkstra",
            "Melissa Duff",
            "Catalina Toma",
            "Bilge Mutlu",
        ],
    },
    {
        title: "SoundHapticVR: Head-Based Spatial Haptic Feedback for Accessible Sounds in Virtual Reality for Deaf and Hard of Hearing Users",
        authors: [
            "Pratheep Kumar Chelladurai",
            "Ziming Li",
            "Maximilian Weber",
            "Tae Oh",
            "Roshan L Peiris",
        ],
    },
    {
        title: "SoundModVR: Sound Modifications in Virtual Reality to Support People who are Deaf and Hard of Hearing",
        authors: ["Xinyun Cao", "Dhruv Jain"],
    },
    {
        title: "The Promise and Pitfalls of Web Accessibility Overlays for Blind and Low Vision Users",
        authors: ["Tlamelo Makati", "Garreth W. Tigwell", "Kristen Shinohara"],
    },
    {
        title: "Towards Accessible Musical Performances in Virtual Reality: Designing a Conceptual Framework for Omnidirectional Audio Descriptions",
        authors: ["Khang Dang", "Grace Burke", "Hamdi Korreshi", "Sooyeon Lee"],
    },
    {
        title: "Towards Construction-Oriented Play for Vision-Diverse People",
        authors: [
            "Adrian Rodriguez",
            "Nisha Devasia",
            "Michelle Pei",
            "Julie A. Kientz",
        ],
    },
    {
        title: "Towards Designing Digital Learning Tools for Students with Cortical/Cerebral Visual Impairments: Leveraging Insights from Teachers of the Visually Impaired",
        authors: ["Adele Smolansky", "Miranda Yang", "Shiri Azenkot"],
    },
    {
        title: "TwIPS: A Large Language Model Powered Texting Application to Simplify Conversational Nuances for Autistic Users",
        authors: ["Rukhshan Haroon", "Fahad Dogar"],
    },
    {
        title: "Uncovering the New Accessibility Crisis in Scholarly PDFs",
        authors: ["Anukriti Kumar", "Lucy Lu Wang"],
    },
    {
        title: "Understanding and Reducing the Challenges Faced by Creators of Accessible Online Data Visualizations",
        authors: [
            "Ather Sharif",
            "Joo Gyeong Kim",
            "Jessie Zijia Xu",
            "Jacob O. Wobbrock",
        ],
    },
    {
        title: "Understanding How Blind Users Handle Object Recognition Errors: Strategies and Challenges",
        authors: ["Jonggi Hong", "Hernisa Kacorri"],
    },
    {
        title: "Understanding Low Vision Graphical Perception of Bar Charts",
        authors: [
            "Yash Prakash",
            "Akshay Kolgar Nayak",
            "Sampath Jayarathna",
            "Hae-Na Lee",
            "Vikas Ashok",
        ],
    },
    {
        title: "Vision-Based Assistive Technologies for People with Cerebral Visual Impairment: A Review and Focus Study",
        authors: [
            "Bhanuka Gamage",
            "Leona M. Holloway",
            "Nicola McDowell",
            "Thanh-Toan Do",
            "Nicholas Seow Chiang Price",
            "Arthur James Lowery",
            "Kim Marriott",
        ],
    },
    {
        title: '"We Musicians Know How to Divide and Conquer": Exploring Multimodal Interactions To Improve Music Reading and Memorization for Blind and Low Vision Learners',
        authors: ["Leon Lu", "Chase Crispin", "Audrey Girouard"],
    },
    {
        title: "WheelPoser: Sparse-IMU Based Body Pose Estimation for Wheelchair Users",
        authors: [
            "Yunzhi Li",
            "Vimal Mollyn",
            "Kuang Yuan",
            "Patrick Carrington",
        ],
    },
];
