export const ORGANIZING_COMMITTEE = [
    {
        heading: "General Chairs",
        members: [
            {
                name: "David Flatla",
                role: "General Chair",
                picture: "/assets/committees/organizing/david_flatla.jpg",
                affiliation: "University of Guelph",
                location: "CANADA",
                email: "general-assets24@acm.org",
            },
            {
                name: "Faustina Hwang",
                role: "General Chair",
                picture: "/assets/committees/organizing/faustina_hwang.jpg",
                affiliation: "University of Reading",
                location: "UNITED KINGDOM",
                email: "general-assets24@acm.org",
            },
        ],
    },
    {
        heading: "Technical Program Chairs",
        members: [
            {
                name: "Tiago Guerreiro",
                role: "Technical Program Chair",
                picture: "/assets/committees/organizing/tiago_guerreiro.png",
                affiliation: "University of Lisbon",
                location: "PORTUGAL",
                email: "tpc-assets24@acm.org",
            },
            {
                name: "Robin Brewer",
                role: "Technical Program Chair",
                picture: "/assets/committees/organizing/robin_brewer.jpeg",
                affiliation: "University of Maryland",
                location: "UNITED STATES",
                email: "tpc-assets24@acm.org",
            },
        ],
    },
    {
        heading: "Treasurer/Registration Chair",
        members: [
            {
                name: "Cynthia Bennett",
                role: "Treasurer/Registration Chair",
                picture: "/assets/committees/organizing/cynthia_bennett.jpeg",
                affiliation: "Google",
                location: "UNITED STATES",
                email: "tpc-assets24@acm.org",
            },
        ],
    },
    {
        heading: "Proceedings Chairs",
        members: [
            {
                name: "Connor Geddes",
                role: "Proceedings Chair",
                picture: "/assets/committees/organizing/connor_geddes.jpeg",
                affiliation: "University of Guelph",
                location: "CANADA",
                email: "tpc-assets24@acm.org",
            },
            {
                name: "André Rodrigues",
                role: "Proceedings Chair",
                picture: "/assets/committees/organizing/andre_rodrigues.jpg",
                affiliation: "University of Lisbon",
                location: "PORTUGAL",
                email: "tpc-assets24@acm.org",
            },
        ],
    },
    {
        heading: "Posters and Demos Chairs",
        members: [
            {
                name: "Garreth Tigwell",
                role: "Posters and Demo Chair 1",
                picture: "/assets/committees/organizing/garreth_tigwell.jpeg",
                affiliation: "Rochester Institute of Technology",
                location: "UNITED STATES",
                email: "tpc-assets24@acm.org",
            },
            {
                name: "Anne Ross",
                role: "Posters and Demo Chair 2",
                picture: undefined,
                affiliation: "Bucknell University",
                location: "UNITED STATES",
                email: "tpc-assets24@acm.org",
            },
        ],
    },
    {
        heading: "DC Chairs",
        members: [
            {
                name: "Kristen Shinohara",
                role: "DC Chair 1",
                picture: "/assets/committees/organizing/kristen_shinohara.jpeg",
                affiliation: "Rochester Institute of Technology",
                location: "UNITED STATES",
                email: "tpc-assets24@acm.org",
            },
            {
                name: "Shari Trewin",
                role: "DC Chair 2",
                picture: "/assets/committees/organizing/shari_trewin.jpeg",
                affiliation: "IBM",
                location: "UNITED STATES",
                email: "tpc-assets24@acm.org",
            },
        ],
    },
    {
        heading: "Web and Graphic Design Chairs",
        members: [
            {
                name: "Suraj Goraya",
                role: "Web and Graphic Design Chair",
                picture: "/assets/committees/organizing/suraj_goraya.jpg",
                affiliation: "University of Guelph",
                location: "CANADA",
                email: "web-assets24@acm.org",
            },
            {
                name: "Ryan Paul",
                role: "Web and Graphic Design Chair",
                picture: "/assets/committees/organizing/ryan_paul.jpg",
                affiliation: "University of Guelph",
                location: "CANADA",
                email: "web-assets24@acm.org",
            },
            {
                name: "Jaipreet Singh",
                role: "Web and Graphic Design Chair",
                picture: "/assets/committees/organizing/jaipreet_singh.jpg",
                affiliation: "Unaffiliated",
                location: "CANADA",
                email: "web-assets24@acm.org",
            },
        ],
    },
];

export const PROGRAM_COMMITTEE = [
    { name: "Abi Roper", school: "University of London", location: "UK" },
    {
        name: "Abigale Stangl",
        school: "University of Washington",
        location: "USA",
    },
    {
        name: "Aboubakar Mountapmbeme",
        school: "University of North Texas",
        location: "USA",
    },
    {
        name: "Afroza Sultana",
        school: "Toronto Metropolitan University",
        location: "Canada",
    },
    {
        name: "Ahmed Sabbir Arif",
        school: "University of California Merced",
        location: "USA",
    },
    {
        name: "Alisha Pradhan",
        school: "New Jersey Institute of Technology",
        location: "USA",
    },
    { name: "Amy Hurst", school: "New York University", location: "USA" },
    {
        name: "Amy Pavel",
        school: "University of Texas at Austin",
        location: "USA",
    },
    {
        name: "Ana Cristina Pires",
        school: "University of Lisbon",
        location: "Portugal",
    },
    {
        name: "André Rodrigues",
        school: "University of Lisbon",
        location: "Portugal",
    },
    {
        name: "Andrew Begel",
        school: "Carnegie Mellon University",
        location: "USA",
    },
    { name: "Anhong Guo", school: "University of Michigan", location: "USA" },
    { name: "Anthony Hornof", school: "University of Oregon", location: "USA" },
    {
        name: "Arthur Theil",
        school: "Birmingham City University",
        location: "UK",
    },
    {
        name: "Ather Sharif",
        school: "University of Washington",
        location: "USA",
    },
    { name: "Barbara Leporini", school: "CNR", location: "Italy" },
    {
        name: "Carlos Duarte",
        school: "Universidade de Lisboa",
        location: "Portugal",
    },
    {
        name: "Catherine Holloway",
        school: "University College London",
        location: "UK",
    },
    {
        name: "Catherine Baker",
        school: "Creighton University",
        location: "USA",
    },
    { name: "Christophe Jouffrais", school: "CNRS", location: "France" },
    {
        name: "Clayton Lewis",
        school: "University of Colorado",
        location: "USA",
    },
    {
        name: "Daisuke Sato",
        school: "Carnegie Mellon University",
        location: "USA",
    },
    { name: "Danielle Bragg", school: "Microsoft Research", location: "USA" },
    { name: "Edward Cutrell", school: "MSR", location: "USA" },
    { name: "Elaine Short", school: "Tufts University", location: "USA" },
    { name: "Erin Brady", school: "IUPUI", location: "USA" },
    { name: "Fabio Paternò", school: "CNR", location: "Italy" },
    {
        name: "Gerhard Weber",
        school: "Dresden University of Technology",
        location: "Germany",
    },
    {
        name: "Giulia Barbareschi",
        school: "Keio University",
        location: "Japan",
    },
    {
        name: "Hernisa Kacorri",
        school: "University of Maryland",
        location: "USA",
    },
    {
        name: "Hironobu Takagi",
        school: "IBM Research Tokyo",
        location: "Japan",
    },
    {
        name: "Hugo Nicolau",
        school: "University of Lisbon",
        location: "Portugal",
    },
    {
        name: "Isabel Neto",
        school: "University of Lisbon",
        location: "Portugal",
    },
    {
        name: "Jacob Wobbrock",
        school: "University of Washington",
        location: "USA",
    },
    {
        name: "Jeffrey Bigham",
        school: "Carnegie Mellon University",
        location: "USA & Apple Research, USA",
    },
    {
        name: "Jiamin (Carrie) Dai",
        school: "University of British Columbia",
        location: "Canada",
    },
    {
        name: "João Guerreiro",
        school: "University of Lisbon",
        location: "Portugal",
    },
    {
        name: "Jodi Forlizzi",
        school: "Carnegie Mellon University",
        location: "USA",
    },
    {
        name: "Jon Froehlich",
        school: "University of Washington",
        location: "USA",
    },
    {
        name: "JooYoung Seo",
        school: "University of Illinois Urbana-Champaign",
        location: "USA",
    },
    {
        name: "Kathleen McCoy",
        school: "University of Delaware",
        location: "USA",
    },
    {
        name: "Kathryn Ringland",
        school: "University of California",
        location: "Santa Cruz, USA",
    },
    { name: "Katta Spiel", school: "TU Wien", location: "Austria" },
    {
        name: "Kotaro Hara",
        school: "Singapore Management University",
        location: "Singapore",
    },
    {
        name: "Krishna Venkatasubramanian",
        school: "University of Rhode Island",
        location: "USA",
    },
    { name: "Lauren Milne", school: "Macalester College", location: "USA" },
    {
        name: "Leah Findlater",
        school: "University of Washington",
        location: "USA & Apple Research, USA",
    },
    { name: "Liang He", school: "Purdue University", location: "USA" },
    { name: "Lynn Kirabo", school: "Harvey Mudd College", location: "USA" },
    {
        name: "Manohar Swaminathan",
        school: "Microsoft Research",
        location: "India",
    },
    { name: "Maria Wolters", school: "OFFIS", location: "Germany" },
    {
        name: "Masatomo Kobayashi",
        school: "IBM Research Tokyo",
        location: "Japan",
    },
    {
        name: "Matt Huenerfauth",
        school: "Rochester Institute of Technology",
        location: "USA",
    },
    { name: "Maulishree Pandey", school: "Google", location: "" },
    {
        name: "Megan Hofmann",
        school: "Northeastern University",
        location: "USA",
    },
    { name: "Michael Crabb", school: "University of Dundee", location: "UK" },
    {
        name: "Mingming Fan",
        school: "The Hong Kong University of Science and Technology (Guangzhou)",
        location: "Hong Kong",
    },
    { name: "Momona Yamagami", school: "Rice University", location: "USA" },
    { name: "Oliver Alonzo", school: "DePaul University", location: "USA" },
    {
        name: "Oussama Metatla",
        school: "University of Bristol",
        location: "UK",
    },
    {
        name: "Ravi Kuber",
        school: "University of Maryland",
        location: "Baltimore County, USA",
    },
    {
        name: "Roshan Peiris",
        school: "Rochester Institute of Technology",
        location: "USA",
    },
    { name: "Rua Williams", school: "Purdue University", location: "USA" },
    { name: "Saad Hassan", school: "Tulane University", location: "USA" },
    {
        name: "Sayan Sarcar",
        school: "Birmingham City University",
        location: "UK",
    },
    {
        name: "Sergio Mascetti",
        school: "University of Milan",
        location: "Italy",
    },
    { name: "Shaomei Wu", school: "Facebook", location: "USA" },
    { name: "Shiri Azenkot", school: "Cornell University", location: "USA" },
    {
        name: "Sidas Saulynas",
        school: "University of Maryland",
        location: "USA",
    },
    { name: "Stacy Branham", school: "UC Irvine", location: "USA" },
    {
        name: "Stephanie Valencia",
        school: "University of Maryland",
        location: "USA",
    },
    {
        name: "Sukru Eraslan",
        school: "Middle East Technical University",
        location: "Turkey",
    },
    {
        name: "Sushil Oswal",
        school: "University of Washington",
        location: "USA",
    },
    {
        name: "Syed Masum Billah",
        school: "Pennsylvania State University",
        location: "USA",
    },
    { name: "Taslima Akter", school: "UC Irvine", location: "USA" },
    { name: "Tim Neate", school: "King’s College London", location: "UK" },
    { name: "Varsha Koushik", school: "Colorado College", location: "USA" },
    {
        name: "William Payne",
        school: "University of North Carolina at Chapel Hill",
        location: "USA",
    },
    {
        name: "Yasmine Elglaly",
        school: "Western Washington University",
        location: "USA",
    },
    {
        name: "Yeliz Yesilada",
        school: "Middle East Technical University",
        location: "Northern Cyprus",
    },
    { name: "Hrishikesh Rao", school: "NewHaptics", location: "USA" },
    { name: "Novia Nurain", school: "University of Michigan", location: "USA" },
    {
        name: "Benjamin Gorman",
        school: "Bournemouth University",
        location: "UK",
    },
    { name: "Erin Buehler", school: "Google", location: "USA" },
    {
        name: "Foad Hamidi",
        school: "University of Maryland",
        location: "Baltimore County, USA",
    },
    {
        name: "Iyad Abu Doush",
        school: "American University of Kuwait",
        location: "Kuwait",
    },
    {
        name: "Jenny Waycott",
        school: "University of Melbourne",
        location: "Australia",
    },
    { name: "Markel Vigo", school: "University of Manchester", location: "UK" },
    {
        name: "Patrick Carrington",
        school: "Carnegie Mellon University",
        location: "USA",
    },
    { name: "Roberto Manduchi", school: "UC Santa Cruz", location: "USA" },
    { name: "Shari Trewin", school: "Google", location: "USA" },
    { name: "Vinod Namboodiri", school: "Lehigh University", location: "USA" },
    {
        name: "Carl Haynes-Magyar",
        school: "Carnegie Mellon University",
        location: "USA",
    },
];
