export const ORGANIZING_COMMITTEE = [
  {
    heading: "General Chairs",
    members: [
      {
        name: "David Flatla",
        role: "General Chair",
        picture: "/assets/committees/organizing/david_flatla.jpg",
        affiliation: "University of Guelph",
        location: "CANADA",
        email: "generalchair-assets24@acm.org",
        alt: "A portrait of David Flatla, a smiling white male with brown hair and short brown beard, wearing a blue and grey sweater.",
      },
      {
        name: "Faustina Hwang",
        role: "General Chair",
        picture: "/assets/committees/organizing/faustina_hwang.jpg",
        affiliation: "University of Reading",
        location: "UNITED KINGDOM",
        email: "generalchair-assets24@acm.org",
        alt: "Black and white headshot of Faustina Hwang, a Taiwanese woman smiling, wearing glasses and a button-up shirt.",
      },
    ],
  },
  {
    heading: "Technical Program Chairs",
    members: [
      {
        name: "Tiago Guerreiro",
        role: "Technical Program Chair",
        picture: "/assets/committees/organizing/tiago_guerreiro.png",
        affiliation: "University of Lisbon",
        location: "PORTUGAL",
        email: "tpc-assets24@acm.org",
        alt: "Headshot of Tiago Guerreiro, a browned-hair man wearing glasses and a blue and white horizontal stripes polo shirt.",
      },
      {
        name: "Robin Brewer",
        role: "Technical Program Chair",
        picture: "/assets/committees/organizing/robin_brewer.jpeg",
        affiliation: "University of Michigan",
        location: "UNITED STATES",
        email: "tpc-assets24@acm.org",
        alt: "Robin Brewer, a black woman smiling with shoulder length curly hair wearing a black lace floral shirt and a patterned orange scarf.",
      },
    ],
  },
  {
    heading: "Treasurer/Registration Chair",
    members: [
      {
        name: "Cynthia Bennett",
        role: "Treasurer/Registration Chair",
        picture: "/assets/committees/organizing/cynthia_bennett.jpeg",
        affiliation: "Google",
        location: "UNITED STATES",
        email: "treasurer-assets24@acm.org",
        alt: "Portrait of Cynthia Bennett, a white woman with long, wavy brown hair. She is wearing a teal-colored shirt and has a cheerful expression.",
      },
    ],
  },
  {
    heading: "Posters and Demos Chairs",
    members: [
      {
        name: "Garreth Tigwell",
        role: "Posters and Demo Chair 1",
        picture: "/assets/committees/organizing/garreth_tigwell.jpeg",
        affiliation: "Rochester Institute of Technology",
        location: "UNITED STATES",
        email: "poster-demo-assets24@acm.org",
        alt: "A portrait of Garreth Tigwell, a white male with dark brown hair, smiling and wearing a dark blue shirt, while in front of a dark background.",
      },
      {
        name: "Anne Ross",
        role: "Posters and Demo Chair 2",
        picture: "/assets/committees/organizing/anne_ross.jpeg",
        // picture: undefined,
        affiliation: "Bucknell University",
        location: "UNITED STATES",
        email: "poster-demo-assets24@acm.org",
        alt: "Headshot of Annie smiling at the camera. She is a white woman in her 30's with curly blonde hair pulled into a bun.",
      },
    ],
  },
  {
    heading: "Proceedings Chairs",
    members: [
      {
        name: "Connor Geddes",
        role: "Proceedings Chair",
        picture: "/assets/committees/organizing/connor_geddes.jpeg",
        affiliation: "University of Guelph",
        location: "CANADA",
        email: "proceedings-assets24@acm.org",
        alt: "Portrait of Connor Geddes, a white man with short dark hair. He is wearing a grey hoodie and is smiling directly at the camera.",
      },
      {
        name: "André Rodrigues",
        role: "Proceedings Chair",
        picture: "/assets/committees/organizing/andre_rodrigues.jpg",
        affiliation: "University of Lisbon",
        location: "PORTUGAL",
        email: "proceedings-assets24@acm.org",
        alt: "Headshot of André, a white man with short hair, glasses and a full short beard. He is staring directly at the camera with a closed-mouth smile and wearing a black long-sleeve shirt.",
      },
    ],
  },
  {
    heading: "Web and Graphic Design Chairs",
    members: [
      {
        name: "Suraj Goraya",
        role: "Web and Graphic Design Chair",
        picture: "/assets/committees/organizing/suraj_goraya.jpg",
        affiliation: "University of Guelph",
        location: "CANADA",
        email: "web-assets24@acm.org",
        alt: "Portrait of Suraj Goraya, a brown man with a beard and glasses, wearing a white turban. He is looking towards the right side of the camera and is dressed in a green jacket over a black t-shirt.",
      },
      {
        name: "Ryan Paul",
        role: "Web and Graphic Design Chair",
        picture: "/assets/committees/organizing/ryan_paul.jpg",
        affiliation: "University of Guelph",
        location: "CANADA",
        email: "web-assets24@acm.org",
        alt: "Portrait of Ryan Paul, a brown man with short dark hair and glasses. He is wearing a green winter jacket, smiling.",
      },
      {
        name: "Jaipreet Singh",
        role: "Web and Graphic Design Chair",
        picture: "/assets/committees/organizing/jaipreet_singh.jpg",
        affiliation: "Unaffiliated",
        location: "CANADA",
        email: "web-assets24@acm.org",
        alt: "Portrait of Jaipreet Singh, a brown man with curly dark hair and a beard. He is wearing a burgundy flannel over a white t-shirt and is smiling directly at the camera.",
      },
    ],
  },
  {
    heading: "Workshop Chairs",
    members: [
      {
        name: "Saad Hassan",
        role: "Workshop Chair 1",
        picture: "/assets/committees/organizing/saad_hassan.jpeg",
        affiliation: "Tulane University",
        location: "UNITED STATES",
        email: "workshops-assets24@acm.org",
        alt: "Portrait of Saad Hassan, a brown, black-haired male with a beard, wearing a light blue dress shirt and peacock green glasses, smiling.",
      },
      {
        name: "Jonggi Hong",
        role: "Workshop Chair 2",
        picture: "/assets/committees/organizing/jonggi_hong.jpg",
        // picture: undefined,
        affiliation: "Stevens Institute of Technology",
        location: "UNITED STATES",
        email: "workshops-assets24@acm.org",
        alt: "Portrait of a smiling Asian man wearing a beige sweater against a dark background.",
      },
    ],
  },
  {
    heading: "Local Arrangements Chair",
    members: [
      {
        name: "Xianta Jiang",
        role: "Local Arrangements 1",
        // picture: undefined,
        picture: "/assets/committees/organizing/xianta_jiang.jpg",
        affiliation: "Memorial University of Newfoundland",
        location: "CANADA",
        email: "local-assets24@acm.org",
        alt: "Headshot of Xianta Jiang, an Asian man smiling and wearing a vertical striped shirt.",
      },
      {
        name: "Taliesin Smith",
        role: "Local Arrangements 2",
        // picture: undefined,
        picture: "/assets/committees/organizing/taliesin_smith.png",
        affiliation: "University of Colorado Boulder",
        location: "UNITED STATES",
        email: "local-assets24@acm.org",
        alt: "Portrait of a smiling woman with short grey hair and glasses, wearing a blue and black printed jacket, standing outside against a blurred background of trees.",
      },
    ],
  },
  {
    heading: "Doctoral Consortium Chairs",
    members: [
      {
        name: "Kristen Shinohara",
        role: "DC Chair 1",
        picture: "/assets/committees/organizing/kristen_shinohara.jpeg",
        affiliation: "Rochester Institute of Technology",
        location: "UNITED STATES",
        email: "dc-chairs-assets24@acm.org",
      },
      {
        name: "Shari Trewin",
        role: "DC Chair 2",
        picture: "/assets/committees/organizing/shari_trewin.jpeg",
        affiliation: "Google",
        location: "UNITED STATES",
        email: "dc-chairs-assets24@acm.org",
        alt: "Shari Trewin, wearing blue wooly clothes as usual, smiling as usual, and outdoors as she wishes was usual!",
      },
    ],
  },
  {
    heading: "Student Research Competition Chairs",
    members: [
      {
        name: "Mauli Pandey",
        role: "Student Research Competition Chair 1",
        picture: "/assets/committees/organizing/mauli_pandey.jpg",
        affiliation: "Google",
        location: "UNITED STATES",
        email: "src-chairs-assets24@acm.org",
        alt: "Mauli Pandey, a brown woman, smiling into the camera and standing against a backdrop of green foliage. She is wearing round black glasses, a blue beanie, and a dark grey jacket.",
      },
      {
        name: "Stephanie Valencia",
        role: "Student Research Competition Chair 2",
        picture: "/assets/committees/organizing/stephanie_valencia.png",
        affiliation: "University of Maryland",
        location: "UNITED STATES",
        email: "src-chairs-assets24@acm.org",
        alt: "Portrait of Stephanie Valencia who is smiling, has blonde hair and is wearing a white knitted sweater.",
      },
    ],
  },
  {
    heading: "Virtual Chairs",
    members: [
      {
        name: "Oliver Alonzo",
        role: "Virtual Chair 1",
        // picture: undefined,
        picture: "/assets/committees/organizing/oliver_alonzo.jpeg",
        affiliation: "DePaul University",
        location: "UNITED STATES",
        email: "virtual-assets24@acm.org",
        alt: "Black and white studio portrait of Oliver Alonzo with a big smile, short black hair and beard, wearing a white shirt.",
      },
      {
        name: "Jesse Martinez",
        role: "Virtual Chair 2",
        // picture: undefined,
        picture: "/assets/committees/organizing/jesse_martinez.jpg",
        affiliation: "University of Washington",
        location: "UNITED STATES",
        email: "virtual-assets24@acm.org",
        alt: "Jesse Martinez, a fair-skinned masc-presenting person with short, wavy brown hair, mild stubble, and a silver eyebrow piercing. He is wearing a pink t-shirt under a denim jacket-hoodie combo and a twisted silver pendant necklace.",
      },
    ],
  },
  {
    heading: "On-site Accessibility Chairs",
    members: [
      {
        name: "Maitraye Das",
        role: "On-site Accessibility 1",
        // picture: undefined,
        picture: "/assets/committees/organizing/maitraye_das.jpg",
        affiliation: "Northeastern University",
        location: "UNITED STATES",
        email: "access-assets24@acm.org",
        alt: "Maitraye, a Brown woman with black shoulder-length straight hair, is smiling at the camera. She is wearing round glasses and a red blazer over a pink shirt.",
      },
      {
        name: "Christopher Power",
        role: "On-site Accessibility 2",
        // picture: undefined,
        picture: "/assets/committees/organizing/christopher_power.jpg",
        affiliation: "University of Prince Edward Island",
        location: "CANADA",
        email: "access-assets24@acm.org",
        alt: "A headshot of Christopher Power wearing a burgundy red jacket and a light blue shirt.",
      },
      {
        name: "Abraham Glasser",
        role: "On-site Accessibility 3",
        // picture: undefined,
        picture: "/assets/committees/organizing/abraham_glasser.jpg",
        affiliation: "Gallaudet University",
        location: "UNITED STATES",
        email: "access-assets24@acm.org",
        alt: "A portrait of Abraham, a white man with curly brown hair, wearing a black dress shirt and hearing aids, and slightly smiling at the camera. The background is blurred.",
      },
    ],
  },
  {
    heading: "Mentoring Chair",
    members: [
      {
        name: "Timothy Neate",
        role: "Mentoring Chair 1",
        // picture: undefined,
        picture: "/assets/committees/organizing/timothy_neate.jpg",
        affiliation: "King's College London",
        location: "UNITED KINGDOM",
        email: "mentoring-assets24@acm.org",
        alt: "Headshot of Timothy Neate, a white, brown-haired male in glasses, wearing a white shirt with colourful Miami scene in the background.",
      },
    ],
  },
  {
    heading: "Student Volunteer Chair",
    members: [
      {
        name: "Humphrey Curtis",
        role: "Student Volunteer Chair 1",
        // picture: undefined,
        picture: "/assets/committees/organizing/humphrey_curtis.jpeg",
        affiliation: "King's College London",
        location: "UNITED KINGDOM",
        email: "sv-chairs-assets24@acm.org",
        alt: "A photograph of Humphrey Curtis, a white male with dark blonde hair, smiling and wearing a grey jumper with dark navy jacket, while in front of a grey and white stone building.",
      },
    ],
  },
  {
    heading: "Experience Report Chair",
    members: [
      {
        name: "Megan Hofmann",
        role: "Experience Report Chair 1",
        // picture: undefined,
        picture: "/assets/committees/organizing/megan_hofmann.jpg",
        affiliation: "Northeastern University",
        location: "UNITED STATES",
        email: "experience-reports-assets24@acm.org",
        alt: "A photo of Megan Hofmann, a White woman with purple hair in a tight bun. Shes wearing a green and black knit dress and bright lipstick. She leans on a lab table in front of a knitting machine.",
      },
    ],
  },

  {
    heading: "Publicity Chair",
    members: [
      {
        name: "Abi Roper",
        role: "Publicity Chair",
        // picture: undefined,
        picture: "/assets/committees/organizing/abi_roper.jpeg",
        affiliation: "City University of London",
        location: "UNITED KINGDOM",
        email: "publicity-assets24@acm.org",
        alt: "Headshot of Abi, a white woman with long, brown, wavy hair, smiling at the camera. She is wearing a black top and brown tortoiseshell glasses. A colourful painting behind Abi shows landmarks along the Dundee skyline.",
      },
    ],
  },

  {
    heading: "TACCESS Special Issue Chair",
    members: [
      {
        name: "LouAnne Boyd",
        role: "TACCESS Special Issue Chair",
        // picture: undefined,
        picture: "/assets/committees/organizing/louAnne_boyd.jpeg",
        affiliation: "Chapman University",
        location: "UNITED STATES",
        email: "taccess-assets24@acm.org",
        alt: "Black and White closeup headshot of me smiling. I am a white woman, my hair is short and gray.",
      },
    ],
  },
];

export const PROGRAM_COMMITTEE = [
  { name: "Abi Roper", school: "University of London", location: "UK" },
  {
    name: "Abigale Stangl",
    school: "University of Washington",
    location: "USA",
  },
  {
    name: "Aboubakar Mountapmbeme",
    school: "University of North Texas",
    location: "USA",
  },
  {
    name: "Afroza Sultana",
    school: "Toronto Metropolitan University",
    location: "Canada",
  },
  {
    name: "Ahmed Sabbir Arif",
    school: "University of California Merced",
    location: "USA",
  },
  {
    name: "Alisha Pradhan",
    school: "New Jersey Institute of Technology",
    location: "USA",
  },
  { name: "Amy Hurst", school: "New York University", location: "USA" },
  {
    name: "Amy Pavel",
    school: "University of Texas at Austin",
    location: "USA",
  },
  {
    name: "Ana Cristina Pires",
    school: "University of Lisbon",
    location: "Portugal",
  },
  {
    name: "André Rodrigues",
    school: "University of Lisbon",
    location: "Portugal",
  },
  {
    name: "Andrew Begel",
    school: "Carnegie Mellon University",
    location: "USA",
  },
  { name: "Anhong Guo", school: "University of Michigan", location: "USA" },
  { name: "Anthony Hornof", school: "University of Oregon", location: "USA" },
  {
    name: "Arthur Theil",
    school: "Birmingham City University",
    location: "UK",
  },
  {
    name: "Ather Sharif",
    school: "University of Washington",
    location: "USA",
  },
  { name: "Barbara Leporini", school: "CNR", location: "Italy" },
  {
    name: "Carlos Duarte",
    school: "Universidade de Lisboa",
    location: "Portugal",
  },
  {
    name: "Catherine Holloway",
    school: "University College London",
    location: "UK",
  },
  {
    name: "Catherine Baker",
    school: "Creighton University",
    location: "USA",
  },
  { name: "Christophe Jouffrais", school: "CNRS", location: "France" },
  {
    name: "Christopher Power",
    school: "University of Prince Edward Island",
    location: "Canada",
  },
  {
    name: "Clayton Lewis",
    school: "University of Colorado",
    location: "USA",
  },
  {
    name: "Daisuke Sato",
    school: "Carnegie Mellon University",
    location: "USA",
  },
  { name: "Danielle Bragg", school: "Microsoft Research", location: "USA" },
  { name: "Edward Cutrell", school: "MSR", location: "USA" },
  { name: "Elaine Short", school: "Tufts University", location: "USA" },
  { name: "Erin Brady", school: "IUPUI", location: "USA" },
  { name: "Fabio Paternò", school: "CNR", location: "Italy" },
  {
    name: "Gerhard Weber",
    school: "Dresden University of Technology",
    location: "Germany",
  },
  {
    name: "Giulia Barbareschi",
    school: "Keio University",
    location: "Japan",
  },
  {
    name: "Hernisa Kacorri",
    school: "University of Maryland",
    location: "USA",
  },
  {
    name: "Hironobu Takagi",
    school: "IBM Research Tokyo",
    location: "Japan",
  },
  {
    name: "Hugo Nicolau",
    school: "University of Lisbon",
    location: "Portugal",
  },
  {
    name: "Isabel Neto",
    school: "University of Lisbon",
    location: "Portugal",
  },
  {
    name: "Jacob Wobbrock",
    school: "University of Washington",
    location: "USA",
  },
  {
    name: "Jeffrey Bigham",
    school: "Carnegie Mellon University",
    location: "USA & Apple Research, USA",
  },
  {
    name: "Jiamin (Carrie) Dai",
    school: "University of British Columbia",
    location: "Canada",
  },
  {
    name: "João Guerreiro",
    school: "University of Lisbon",
    location: "Portugal",
  },
  {
    name: "Jodi Forlizzi",
    school: "Carnegie Mellon University",
    location: "USA",
  },
  {
    name: "Jon Froehlich",
    school: "University of Washington",
    location: "USA",
  },
  {
    name: "JooYoung Seo",
    school: "University of Illinois Urbana-Champaign",
    location: "USA",
  },
  {
    name: "Kathleen McCoy",
    school: "University of Delaware",
    location: "USA",
  },
  {
    name: "Kathryn Ringland",
    school: "University of California",
    location: "Santa Cruz, USA",
  },
  { name: "Katta Spiel", school: "TU Wien", location: "Austria" },
  {
    name: "Kotaro Hara",
    school: "Singapore Management University",
    location: "Singapore",
  },
  {
    name: "Krishna Venkatasubramanian",
    school: "University of Rhode Island",
    location: "USA",
  },
  { name: "Lauren Milne", school: "Macalester College", location: "USA" },
  {
    name: "Leah Findlater",
    school: "University of Washington",
    location: "USA & Apple Research, USA",
  },
  { name: "Liang He", school: "Purdue University", location: "USA" },
  { name: "Lynn Kirabo", school: "Harvey Mudd College", location: "USA" },
  {
    name: "Manohar Swaminathan",
    school: "Microsoft Research",
    location: "India",
  },
  { name: "Maria Wolters", school: "OFFIS", location: "Germany" },
  { name: "Michele Williams", school: "M.A.W. Consulting", location: "USA" },
  {
    name: "Masatomo Kobayashi",
    school: "IBM Research Tokyo",
    location: "Japan",
  },
  {
    name: "Matt Huenerfauth",
    school: "Rochester Institute of Technology",
    location: "USA",
  },
  { name: "Maulishree Pandey", school: "Google", location: "" },
  {
    name: "Megan Hofmann",
    school: "Northeastern University",
    location: "USA",
  },
  { name: "Michael Crabb", school: "University of Dundee", location: "UK" },
  {
    name: "Mingming Fan",
    school: "The Hong Kong University of Science and Technology (Guangzhou)",
    location: "Hong Kong",
  },
  { name: "Momona Yamagami", school: "Rice University", location: "USA" },
  { name: "Oliver Alonzo", school: "DePaul University", location: "USA" },
  {
    name: "Oussama Metatla",
    school: "University of Bristol",
    location: "UK",
  },
  {
    name: "Ravi Kuber",
    school: "University of Maryland",
    location: "Baltimore County, USA",
  },
  {
    name: "Roshan Peiris",
    school: "Rochester Institute of Technology",
    location: "USA",
  },
  { name: "Rua Williams", school: "Purdue University", location: "USA" },
  { name: "Saad Hassan", school: "Tulane University", location: "USA" },
  {
    name: "Sayan Sarcar",
    school: "Birmingham City University",
    location: "UK",
  },
  {
    name: "Sergio Mascetti",
    school: "University of Milan",
    location: "Italy",
  },
  { name: "Shaomei Wu", school: "Facebook", location: "USA" },
  { name: "Shiri Azenkot", school: "Cornell University", location: "USA" },
  {
    name: "Sidas Saulynas",
    school: "University of Maryland",
    location: "USA",
  },
  { name: "Stacy Branham", school: "UC Irvine", location: "USA" },
  {
    name: "Stephanie Valencia",
    school: "University of Maryland",
    location: "USA",
  },
  {
    name: "Sukru Eraslan",
    school: "Middle East Technical University",
    location: "Turkey",
  },
  {
    name: "Sushil Oswal",
    school: "University of Washington",
    location: "USA",
  },
  {
    name: "Syed Masum Billah",
    school: "Pennsylvania State University",
    location: "USA",
  },
  { name: "Taslima Akter", school: "UC Irvine", location: "USA" },
  { name: "Tim Neate", school: "King’s College London", location: "UK" },
  { name: "Varsha Koushik", school: "Colorado College", location: "USA" },
  {
    name: "William Payne",
    school: "University of North Carolina at Chapel Hill",
    location: "USA",
  },
  {
    name: "Yasmine Elglaly",
    school: "Western Washington University",
    location: "USA",
  },
  {
    name: "Yeliz Yesilada",
    school: "Middle East Technical University",
    location: "Northern Cyprus",
  },
  { name: "Hrishikesh Rao", school: "NewHaptics", location: "USA" },
  { name: "Novia Nurain", school: "University of Michigan", location: "USA" },
  {
    name: "Benjamin Gorman",
    school: "Bournemouth University",
    location: "UK",
  },
  { name: "Erin Buehler", school: "Google", location: "USA" },
  {
    name: "Foad Hamidi",
    school: "University of Maryland",
    location: "Baltimore County, USA",
  },
  {
    name: "Iyad Abu Doush",
    school: "American University of Kuwait",
    location: "Kuwait",
  },
  {
    name: "Jenny Waycott",
    school: "University of Melbourne",
    location: "Australia",
  },
  { name: "Markel Vigo", school: "University of Manchester", location: "UK" },
  {
    name: "Patrick Carrington",
    school: "Carnegie Mellon University",
    location: "USA",
  },
  { name: "Roberto Manduchi", school: "UC Santa Cruz", location: "USA" },
  { name: "Shari Trewin", school: "Google", location: "USA" },
  {
    name: "Yuhang Zhao",
    school: "University of Wisconsin-Madison",
    location: "USA",
  },
  { name: "Simon Harper", school: "University of Manchester", location: "UK" },
  {
    name: "Franklin Mingzhe Li",
    school: "Carnegie Mellon University",
    location: "USA",
  },
  {
    name: "Matthew Butler",
    school: "Monash University",
    location: "Australia",
  },
  { name: "Vinod Namboodiri", school: "Lehigh University", location: "USA" },
  {
    name: "Carl Haynes-Magyar",
    school: "Carnegie Mellon University",
    location: "USA",
  },
];
