const KEYNOTE_SPEAKERS = [
  {
    name: "Dr. Chieko Asakawa",
    picture: "/assets/keynote-speakers/dr_chieko_asakawa.jpg",
    alt: "Portrait of Dr. Chieko Asakawa, recipient of the 2024 SIGACCESS Award for Outstanding Contributions",
    bio: "I have been working on the area of accessibility for many years. I started by helping people with visual impairments to access  information. Our Braille digitalization project helped change from the paper era to the digital Braille era. This was the first  major focus of my career. Then I worked to improve the Web accessibility beginning in the mid 1990s. My major projects included Home Page Reader so visually impaired people could surf the Web, aDesigner for developers, ai-browser for  multimedia content accessibility, and Social Accessibility, a system to adapt the power of crowdsourcing to improve Web accessibility.\n\nMy recent research work is focusing on the real-world accessibility aiming at supplementing or augmenting  missing or weakened abilities of people with disabilities and elderly people by the power of artificial intelligence. As the first step, I worked on NavCog, an indoor navigation system for the blind that allows them to move around indoor  locations such as schools, hospitals, airports, shopping malls, and so on. Then, I moved on to the AI suitcase, a navigational  mobility robot, that helps the blind explore in a city. The robot recognizes surrounding information, such as pedestrians, obstacles for the safe navigation.\n\nIn recognition of my sustained contributions to making the world more accessible, in 2013, I was awarded the Shiju-hosho (officially translated as the Medal of Honor with Purple Ribbon). This is the highest of six awards granted by the Emperor of  Japan based on the Japanese Cabinet's recognition of outstanding contributions to society in science or the arts. In 2017, I was inducted to be a foreign member of US National Academy of Engineering. In 2019, I was inducted into US National Inventors Hall of Fame, and was awarded the IPO Inventor of the Year.",
  },
];
export { KEYNOTE_SPEAKERS };
